export interface Project {
  title: string;
  description: string;
  tags: string[];
  github?: string;
  repos?: { label: string; url: string }[];
  demo?: string;
  featured?: boolean;
}

export const projects: Project[] = [
  {
    title: "ASC - Ayendah Sazan Community",
    description:
      "A client platform for the Ayendah Sazan community in Leeds, combining venue booking, event tickets, course enrolment, and sports team registration. Stripe handles both subscriptions and one-off payments, with three-tier role-based access control. Fully tested, with a GitHub Actions pipeline that deploys to Vercel when tests pass.",
    tags: ["React", "JavaScript", "Express", "MongoDB", "Stripe", "Cloudinary", "TanStack Query", "Jest", "React Testing Library", "GitHub Actions"],
    repos: [
      { label: "Frontend repository", url: "https://github.com/karimhafiz/ascFront" },
      { label: "Backend repository", url: "https://github.com/karimhafiz/ascBack" },
    ],
    demo: "https://asc-lac.vercel.app",
    featured: true,
  },
  {
    title: "Passerine",
    description:
      "A Letterboxd-style movie & TV tracker. Search the TMDB catalog, track titles with watch statuses (Plan to Watch → Completed), rate on a half-star scale with written reviews, and browse other users' reviews. NextAuth v5 auth (Google OAuth + credentials), PostgreSQL on Supabase via Prisma, Tailwind v4 + shadcn/ui, deployed on Vercel.",
    tags: ["Next.js 16", "TypeScript", "NextAuth", "Prisma", "PostgreSQL", "Supabase", "Tailwind CSS", "TMDB API"],
    github: "https://github.com/yaisnw/passerine",
    demo: "https://passerine.vercel.app",
    featured: true,
  },
  {
    title: "Blogging Platform",
    description:
      "Full-stack blogging platform with a Lexical rich-text editor, Google OAuth, AWS S3 image uploads, and a fully typed React 19 + Express + PostgreSQL stack. Deployed via Vercel with Docker images published to Docker Hub.",
    tags: ["TypeScript", "React 19", "Redux Toolkit", "Express", "PostgreSQL", "AWS S3", "Docker"],
    github: "https://github.com/yaisnw/blogging-platform",
    demo: "https://blogging-platform-pearl-six.vercel.app/",
    featured: true,
  },
  {
    title: "E-Commerce App",
    description:
      "Full-stack e-commerce storefront — React + Redux client with cart, checkout, and Framer Motion animations, backed by a Node/Express REST API with Passport.js + JWT auth, order processing, and bcrypt-hashed accounts. PostgreSQL on Supabase, deployed on Render.",
    tags: ["React", "Redux", "Node.js", "Express", "PostgreSQL", "Passport.js", "JWT", "Supabase"],
    github: "https://github.com/yaisnw/ecommerceclient",
  },
  {
    title: "GitHub Analyser",
    description:
      "An AI agent that reads a public GitHub repository and writes a plain-text analysis of it. Gemini runs a tool-calling loop, choosing which files to read, fetching them in parallel from the GitHub REST API, and stopping once it has enough context to explain what the project is and how it's built. Built to run on the free tier: requests are spaced to respect Gemini's rate limits, large files are trimmed, failed file reads go back to the model instead of ending the run, and each failure type returns its own error message.",
    tags: ["Next.js 16", "React 19", "TypeScript", "Tailwind CSS", "Gemini API", "GitHub REST API"],
    github: "https://github.com/yaisnw/github-analyser",
  },
  {
    title: "Jammming",
    description:
      "A Spotify-powered playlist builder. Search tracks, compose custom playlists, and save them straight to your Spotify account via OAuth and the Web API.",
    tags: ["React", "Spotify Web API", "OAuth"],
    github: "https://github.com/yaisnw/Jammming",
  },
  {
    title: "Reddit Client",
    description:
      "A Reddit browser with search, New/Top filtering, and full media support — images, galleries, and videos render without conflicts. Recently revisited to fix gallery resolution and video/thumbnail rendering bugs.",
    tags: ["React", "Redux Toolkit", "Reddit JSON API"],
    github: "https://github.com/yaisnw/reddit-clone",
    demo: "https://yaisnw.github.io/reddit-clone",
  },
  {
    title: "Cover Letter Generator",
    description:
      "Paste a job description, upload your resume as a PDF, and get a tailored cover letter generated by Google Gemini. A Next.js Server Function keeps the API key on the server, with inline validation and error handling, one-click copy, and localStorage persistence. Tested with Jest and React Testing Library (Gemini SDK mocked), with a GitHub Actions pipeline running build and tests on every push and pull request.",
    tags: ["Next.js 16", "React 19", "TypeScript", "Tailwind CSS", "Gemini API", "Jest", "React Testing Library", "GitHub Actions"],
    github: "https://github.com/yaisnw/cover-letter-generator",
    demo: "https://cover-letter-generator-yasin.vercel.app",
  },
  {
    title: "Uptime Monitor",
    description:
      "A lightweight service monitoring API that checks the uptime and response times of external services concurrently, with httpx handling the concurrent requests. Currently watching GitHub, Stripe, Cloudinary, Supabase, Vercel, and MongoDB Atlas.",
    tags: ["Python", "FastAPI", "httpx"],
    github: "https://github.com/yaisnw/uptime-monitor",
  },
  {
    title: "notesAPI",
    description:
      "REST API built with Python, FastAPI, and PostgreSQL. Full CRUD with SQLModel ORM.",
    tags: ["Python", "FastAPI", "PostgreSQL", "SQLModel"],
    github: "https://github.com/yaisnw/notesApi",
  },
];
